cmake_minimum_required (VERSION 3.24 FATAL_ERROR)

include(${CMAKE_CURRENT_LIST_DIR}/../utils/missing_error.cmake)

macro(add_gtest)
  if (NOT TARGET GTest::gtest)
    find_package(GTest QUIET)
    if (NOT TARGET GTest::gtest)
      set(SOURCE_DIR ${CPP_CORE_SOURCE_DIR}/components/googletest)
      set(BINARY_DIR ${CPP_CORE_BINARY_DIR}/components/googletest)
      if (NOT EXISTS ${SOURCE_DIR})
	missing_error(Gtest GTest::gtest ${SOURCE_DIR})
      endif()
      add_subdirectory(${SOURCE_DIR} ${BINARY_DIR})
    endif()
  endif()
endmacro()
