cmake_minimum_required (VERSION 3.24 FATAL_ERROR)

function(add_boost_sort)
  add_repo(array REPO boostorg TAG boost-1.82.0)
  add_repo(assert REPO boostorg TAG boost-1.82.0)
  add_repo(bind REPO boostorg TAG boost-1.82.0)
  add_repo(concept_check REPO boostorg TAG boost-1.82.0)
  add_repo(config REPO boostorg TAG boost-1.82.0)
  add_repo(container_hash REPO boostorg TAG boost-1.82.0)
  add_repo(conversion REPO boostorg TAG boost-1.82.0)
  add_repo(core REPO boostorg TAG boost-1.82.0)
  add_repo(describe REPO boostorg TAG boost-1.82.0)
  add_repo(detail REPO boostorg TAG boost-1.82.0)
  add_repo(function REPO boostorg TAG boost-1.82.0)
  add_repo(function_types REPO boostorg TAG boost-1.82.0)
  add_repo(functional REPO boostorg TAG boost-1.82.0)
  add_repo(fusion REPO boostorg TAG boost-1.82.0)
  add_repo(io REPO boostorg TAG boost-1.82.0)
  add_repo(iterator REPO boostorg TAG boost-1.82.0)
  add_repo(move REPO boostorg TAG boost-1.82.0)
  add_repo(mpl REPO boostorg TAG boost-1.82.0)
  add_repo(mp11 REPO boostorg TAG boost-1.82.0)
  add_repo(optional REPO boostorg TAG boost-1.82.0)
  add_repo(predef REPO boostorg TAG boost-1.82.0)
  add_repo(preprocessor REPO boostorg TAG boost-1.82.0)
  add_repo(range REPO boostorg TAG boost-1.82.0)
  add_repo(regex REPO boostorg TAG boost-1.82.0)
  add_repo(smart_ptr REPO boostorg TAG boost-1.82.0)
  add_repo(sort REPO boostorg TAG develop)
  add_repo(static_assert REPO boostorg TAG boost-1.82.0)
  add_repo(throw_exception REPO boostorg TAG boost-1.82.0)
  add_repo(typeof REPO boostorg TAG boost-1.82.0)
  add_repo(type_traits REPO boostorg TAG boost-1.82.0)
  add_repo(tuple REPO boostorg TAG boost-1.82.0)
  add_repo(utility REPO boostorg TAG boost-1.82.0)
endfunction()
