cmake_minimum_required (VERSION 3.24 FATAL_ERROR)

include(${CMAKE_CURRENT_LIST_DIR}/add_chrono.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/add_date.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/add_fmt.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/add_gtest.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/add_fp.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/add_json.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/add_mp.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/add_pp.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/add_stream.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/add_strand.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/add_string.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/add_tuple.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/add_util.cmake)
