cmake_minimum_required (VERSION 3.24 FATAL_ERROR)

include(FetchContent)
include(${CMAKE_CURRENT_LIST_DIR}/add_component.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/compile_commands.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/configure_tests.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/convenience_targets.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/install_config.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/missing_error.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/return_if_target.cmake)
